name: Android Release Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Commit Count
        id: vars
        run: echo "commit_count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      - name: Build Release APK
        run: ./gradlew assembleRelease -PversionCode=${{ steps.vars.outputs.commit_count }} -PversionName="1.0.3"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
          tag_name: "android-v${{ steps.vars.outputs.commit_count }}"
          name: "Android Release 1.0.3 (${{ steps.vars.outputs.commit_count }})"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
